### ISSUE TITLE
New Instance

### ISSUE THREAD

**Issue by TechnicalSuwako** [iv-org/documentation#119]
Please add → https://youtube.076.ne.jp
Sarver rocation: japan

**Comment by syeopite** [comment]
That... Is a **major** AGPL violation. The AGPL licence requires all distribution (network included) to disclose their source code and clearly state changes.

Until you provide those information, I'm afraid we can't add your instance onto the official list.

**Comment by TechnicalSuwako** [comment]
@syeopite 
https://git.076.ne.jp/TechnicalSuwako/invidious-mod/-/commit/a87e94b9816ff15688706a957de1a19e45538fe6

**Comment by SamantazFox** [comment]
> @syeopite
> https://git.076.ne.jp/TechnicalSuwako/invidious-mod/-/commit/a87e94b9816ff15688706a957de1a19e45538fe6

Just for your information: most of the changes you made to the source code may (and are going to) break invidious. I won't detail here why, but be aware that, in general, the `gl` parameter (geographic region) can be changed but not the `hl` (locale/language), as it influences the text data returned by youtube, which is heavily used by our parser (i.e, the parser matches `x views` to get a viewcount, so that won't work with the japanese word for `views`).

A rework of the available options is in progress, so in the future the region will be configurable without having to mess with the code!

In the meantime, feel free to ping me if you need a more in depth review of it :)

**Comment by TechnicalSuwako** [comment]
I'll change it.
https://git.076.ne.jp/TechnicalSuwako/invidious-mod/-/commit/f8d4820740b15a32904a5d117296e8e4c5b946f1
Please check it out.

**Comment by SamantazFox** [comment]
@TechnicalSuwako Yeah, that's much better :)

Btw, for the default locale, don't modify the source code directly. Instead use the config option for that matter:
https://git.076.ne.jp/TechnicalSuwako/invidious-mod/-/commit/f8d4820740b15a32904a5d117296e8e4c5b946f1#59c4f02b4ed5c42144db4086446aa59b37f4674b_41_39

This is documented in the example config file:
https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L457-L496

**Comment by SamantazFox** [comment]
Also, please enable statistics! https://youtube.076.ne.jp/api/v1/stats

**Comment by TechnicalSuwako** [comment]
I've changed it.

**Comment by unixfox** [comment]
@TechnicalSuwako could you please keep your instance up to date? it is more than one month old
