### ISSUE TITLE
[New instance] https://invidious.lunar.icu

### ISSUE THREAD

**Issue by MaximilianGT500** [iv-org/documentation#321]
### URL

https://invidious.lunar.icu

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Man in the Middle

CloudFlare

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Added to uptime robot: https://stats.uptimerobot.com/89VnzSKAn/793362057

**Comment by unixfox** [comment]
Please double-check that you have configured `hmac_key` in the config file or INVIDIOUS_CONFIG then restart the instance.

You must set a random generated value for the parameter `hmac_key:`! On Linux, you can generate it using the command `pwgen 20 1`.

**Comment by MaximilianGT500** [comment]
Done

**Comment by unixfox** [comment]
Please consider joining our Matrix room for public instance maintainers by joining our Matrix room: https://matrix.to/#/#invidious:matrix.org
then pinging @unixfox, @TheFrenchGhosty and @SamantazFox for asking to be invited to the Matrix room.
We discuss troubles managing a public instance, sharing some advices and more.

**Comment by unixfox** [comment]
@MaximilianGT500 

Hello, your instance is affected by this new issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

**Comment by MaximilianGT500** [comment]
Hello, I will have a closer look at this tonight. I also think I will be able to change the IP.

**Comment by unixfox** [comment]
Hello @MaximilianGT500,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because your instance is unfortunately in a state where it is not working well for your users.

If you need help please either ask in the invidious room on matrix or here.
