### ISSUE TITLE
[New instance] https://invidious.nogafa.org

### ISSUE THREAD

**Issue by dannielou** [iv-org/documentation#358]
### URL

https://invidious.nogafa.org

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

fr

### Man in the Middle

ovh ddos protection

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

IPV4 only :( maybe later

Some iptables filtering is done

No analytics

**Comment by unixfox** [comment]
Added on uptime robot: https://stats.uptimerobot.com/89VnzSKAn/794069070

**Comment by unixfox** [comment]
@dannielou 

Hello, your instance is affected by this new issue: https://github.com/iv-org/invidious/issues/3822

Please have a look for a temporary solution: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621

**Comment by unixfox** [comment]
Hello,

We temporarily removed your instance in order to avoid the Invidious users to use an instance that doesn't work for the moment.

Once you have fixed the issue (`The video returned by YouTube isn't the requested one. (WEB client) (VideoNotAvailableException)`) on your instance, please ask to get your instance back in the list.

We are fully aware that this issue is not your fault, but for the moment we can't do anything than filtering in the list the instances that works from the instances that don't. Again, like said previously, we are working on the problem, and all progress will be posted in [#3822](https://github.com/iv-org/invidious/issues/3822).

Thank you for your understanding.

**Comment by unixfox** [comment]
I have updated my comment to provide an easy docker-compose file for adding ipv6: https://github.com/iv-org/invidious/issues/3822#issuecomment-1565401621
