### ISSUE TITLE
[New instance] invidious.12a.app

### ISSUE THREAD

**Issue by angus6b23** [iv-org/documentation#447]
### URL

https://invidious.12a.app

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Netherland

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

Download is disabled.

**Comment by unixfox** [comment]
Hello @angus6b23,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because it will allow the instance to stay very stable and performant over the long term.

If you need help please either ask in the invidious room on matrix or here.

**Comment by angus6b23** [comment]
Thank You for the information. I would try to implement the suggestions.

**Comment by unixfox** [comment]
@angus6b23 did you implement the suggestions?

**Comment by angus6b23** [comment]
Yes, i have implemented the ipv6 rotation and multiple process as suggested.
