### ISSUE TITLE
[New instance] https://invidious.privacyfucking.rocks

### ISSUE THREAD

**Issue by HeyMika** [iv-org/documentation#448]
### URL

https://invidious.privacyfucking.rocks

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Source code URL

https://github.com/iv-org/invidious

### Analytics

- [ ] They are GDPR/CCPA compliant
- [X] This is stated in your Privacy Policy
- [X] You have provided the source code's URL in the dedicated field above

**Comment by unixfox** [comment]
Hello @HeyMika,

We have recently released two major tutorials for improving your public instance.

- Escaping the YouTube block (403 errors in playback): https://docs.invidious.io/ipv6-rotator/
- Improving the performance and the stability of your public instance: https://docs.invidious.io/improve-public-instance/

We highly recommend you to follow our tutorials because it will allow the instance to stay very stable and performant over the long term.

If you need help please either ask in the invidious room on matrix or here.

**Comment by HeyMika** [comment]
Alright, thanks for the info!

**Comment by unixfox** [comment]
@HeyMika did you implement the suggestions? at least the first one, it's now mandatory.

**Comment by unixfox** [comment]
Closing due to lack of replies.

Please ask to reopen when the answer has been given for my question above.
