### ISSUE TITLE
[New instance] invidious.jing.rocks

### ISSUE THREAD

**Issue by delgh1** [iv-org/documentation#489]
### URL

https://invidious.jing.rocks

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Japan

### Man in the Middle

None

### Source code URL

https://forgejo.jing.rocks/jing/invidious.git

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

(1) I did not change the source code, it's merely a mirror. (2) auto rotate ipv6 is done, but using "http3-ytproxy" is not implemented for now (3) ping @unixfox @TheFrenchGhosty @SamantazFox :)

**Comment by epman100** [comment]
hello.

As of 12/11/2024, this instance appears to be more than a month out of date and has recently stopped
working (no longer follows [rule #2](https://docs.invidious.io/instances/#rules-to-have-your-instance-in-this-list))

Please contact the owner or OP of the invidious.jing.rocks instance to have it updated as soon
as possible and online again; otherwise it should be taken off the [list of public Invidious instances](https://docs.invidious.io/instances/).
thanks.
