### ISSUE TITLE
[New instance] inv.oikei.net

### ISSUE THREAD

**Issue by notyuuko** [iv-org/documentation#495]
### URL

https://inv.oikei.net

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additional information

I havent set up the ipv6 rotator yet.

**Comment by perennialtech** [comment]
@notyuuko Any update on setting up the IPv6 rotator?

A few other things:

- Your instance a bit out of date at the moment (`2024.02.19-e8a36985`, whereas the latest version is `2024.03.08-99a5e9c`). If you're using Docker, you can use something like [Watchtower](https://github.com/containrrr/watchtower/) to automatically update Invidious to the latest image.
- While it's not required, you may also want to remove the [`X-XSS-Protection`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) header, since it's been deprecated for a while now and no modern browser supports it.

Other than that, your instance looks fine to added to the list.

**Comment by notyuuko** [comment]
> @notyuuko Any update on setting up the IPv6 rotator?
yep, i set it up on the instance already
> Your instance a bit out of date at the moment
updated it to latest
>While it's not required, you may also want to remove the X-XSS-Protection header
thanks for the notice, disabled it

thanks

**Comment by perennialtech** [comment]
@notyuuko I've added your instance to the list, but you should still address a couple other things:

- You haven't actually disabled the `X-XSS-Protection` header entirely. Instead, you're setting the header twice, once with `1; mode=block` and the other with `0`. Since you're using nginx, you might find the `more_clear_headers` directive, part of the [`ngx_headers_more`](https://github.com/openresty/headers-more-nginx-module) module, useful.
- You should also enable HTTP/2 and HTTP/3 on your instance to improve its performance.
- If you haven't already, see the [Improve your public instance performance and stability](https://docs.invidious.io/improve-public-instance/) page on the Invidious docs.
