### ISSUE TITLE
[New instance] vid.lilay.dev

### ISSUE THREAD

**Issue by Addi-Here** [iv-org/documentation#502]
### URL

https://vid.lilay.dev

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Singapore 

### Man in the Middle

Cloudflare 

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

**Comment by perennialtech** [comment]
@Addi-Here A few things you need to address on your instance before it can be added:

- Please disable [Cloudflare Web Analytics](https://developers.cloudflare.com/analytics/web-analytics/) on your instance.
  ```html
  <script
    defer
    src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317"
    integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA=="
    data-cf-beacon='{"rayId":"864914638968a968","r":1,"version":"2024.2.4","token":"3876942efc0743b896e320f9c6ac4376"}'
    crossorigin="anonymous"
  ></script>
  ```
- The `Modified source code` item appears in the footer, but doesn't link to an external repository. Check your [config.yml](https://github.com/iv-org/invidious/blob/master/config/config.example.yml).
- While it's not required, you may also want to remove the [`X-XSS-Protection`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) header, since it's been deprecated for a while now and no modern browser supports it.

**Comment by Addi-Here** [comment]
@perennialtech Hi, I have resolved all the things you have mention above. Feel free to check!
Also IPv6 rotator working fine!

**Comment by perennialtech** [comment]
@li-lay Your instance has been temporarily removed from the official list (https://github.com/iv-org/documentation/commit/527dc1684ab8584df8ef2e08d519ef49fa1ee072).

Prior to adding your instance to the list, you were asked to remove tracking scripts (https://github.com/iv-org/documentation/issues/502#issuecomment-1998839918). While these scripts were not present when your instance was initially added, it appears they have since been re-added to the instance.

In order to be added back to the official list, you must remove these scripts from your instance.

**Please note that this will be your only warning regarding this issue.** If tracking scripts are found on your instance again in the future, it will be permanently blacklisted from the official list.

<details>
<summary><h3>Tracking script found on the instance (click to expand)<h3></summary>
<pre>
<code>
<script
  src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js"
  data-cf-settings="bfe5cc1c043320662154b550-|49"
  defer
></script>
<script
  defer
  src="https://static.cloudflareinsights.com/beacon.min.js/vef91dfe02fce4ee0ad053f6de4f175db1715022073587"
  integrity="sha512-sDIX0kl85v1Cl5tu4WGLZCpH/dV9OHbA4YlKCuCiMmOQIk4buzoYDZSFj+TvC71mOBLh8CDC/REgE0GX0xcbjA=="
  data-cf-beacon='{"rayId":"88de75717eeda980","r":1,"version":"2024.4.1","token":"77eff00774454b2f9df8400998adc73b"}'
  crossorigin="anonymous"
></script>
</code>
</pre>
</details>

**Comment by li-lay** [comment]
@perennialtech I sincerely apologize for this oversight. The inclusion of these scripts was unintentional and occurred without my notice when I was optimizing my other domain on Cloudflare back 11 days ago.

I have now removed all tracking scripts from my instances. Please verify the changes at your earliest convenience.

I understand the importance of maintaining the integrity and privacy standards of the official list and assure you that this issue will not recur. I appreciate your understanding and the opportunity to correct this mistake. I hope you understand me.

**Comment by perennialtech** [comment]
@li-lay You've disabled Cloudflare Web Analytics, but [Rocket Loader](https://developers.cloudflare.com/speed/optimization/content/rocket-loader/) is still enabled on your instance. Please disable it.

See https://github.com/iv-org/documentation/pull/565 for more information on this.

**Comment by li-lay** [comment]
@perennialtech I believed it already done! Let me purge the cache.
