### ISSUE TITLE
[New instance] https://just4cats.tv

### ISSUE THREAD

**Issue by ravxmr** [iv-org/documentation#526]
### URL

https://just4cats.tv

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Canada

### Additional information

Internet connection is symmetrical 1.5GB (soon 3GB)

**Comment by perennialtech** [comment]
**Added to monitoring: https://updown.io/0cw8**

@ravxmr Instance looks mostly good, but a few things you might want to address:

- **(Required)** Make sure you've completed the steps on [Improve your public instance performance and stability](https://docs.invidious.io/improve-public-instance/).

- **(Optional)** Check that you have HTTP/2 enabled (and HTTP/3, if possible).

- **(Optional)** You may also want to remove the [`X-XSS-Protection` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection), since it's been deprecated for a while now and no modern browser supports it.

**Comment by bugmaschine** [comment]
@ravxmr Your instance still does not have IPv6 connectivity, untill this issue is fixed we cannot add your instance to the public instance list.

**Comment by unixfox** [comment]
> @ravxmr Your instance still does not have IPv6 connectivity, untill this issue is fixed we cannot add your instance to the public instance list.

it's ok to not have ipv6 connectivity on the frontend side. what matters is that the instance can rotate its IP addresses using ipv6.

**Comment by ravxmr** [comment]
Hi, It's going to have to wait.
The ISP can't provide ipv6 at the location so my plan was to use VPS(s) and use them for the ipv6 connectivity.

I am waiting for replacement network equipment as what I have right now is limit (Using the Internet to half it's maximum speed of 3GB/s also bring the router to ~100% CPU utilization. Adding VPN configurations to import my ipv6 from the vps would be too much.

Have to put that on ice, until I get the new router for that location.

**Comment by unixfox** [comment]
Please ask us to reopen when you have fixed your instance, for the moment it is not working.
