### ISSUE TITLE
[New instance] https://invidious.incogniweb.net

### ISSUE THREAD

**Issue by viaguy** [iv-org/documentation#532]
### URL

https://invidious.incogniweb.net/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Additional information

The instance is served by Nginx and supports all the sweet new HTTP protocols. [http3check.net results](https://http3check.net/?host=https%3A%2F%2Finvidious.incogniweb.net)

The instance banner is a link to my site homepage that lists the other open source front ends I host. On the page is also a link that allows users to donate to help support server costs if they wish. I don't _think_ this violates rule 12 on the public instance rules, since its not for profit and I'm not selling anything. But I should mention it anyway for the sake of transparency.

Currently, dash and proxy are disabled by default (but still available for users to enable) due to bandwidth limitations. I am working on upgrading the available bandwidth on my VPS plan as I would really prefer to enable dash and proxy for all by default. Though it may not be possible for me to afford 100TB+ of bandwidth per month without donation support.

I'm using the default captcha shipped with invidious (`captcha_enabled: true`)

The instance is using my own implementation of IPv6 rotation to avoid youtube blocking, by leveraging [RFC 8981
Temporary Address Extensions](https://www.rfc-editor.org/rfc/rfc8981) and the [net.ipv6.conf.eth0.use_tempaddr=2](https://sysctl-explorer.net/net/ipv6/use_tempaddr/) linux kernel setting. This causes applications to make outgoing v6 connections from the randomly generated address instead of the static IPv6 address unless otherwise specified. I also have modified the expire time of temporary addresses to limit their preferred lifetime to 1 hour, for more frequent address changes.

As I have my system configured:
Nginx front end listens for connections on IPv4 & the static IPv6 address of the server.
The Invidious backend makes outgoing connections from the dynamic IPv6 privacy address.

**Comment by perennialtech** [comment]
@viaguy Apologies for the delay in reviewing your instance. 

I've taken a look and the instance uptime looks good. Video playback is working perfectly with your custom IPv6 rotation implementation. Nice work on this.

The announcements you've posted about instance downtime are also appreciated. As a suggestion, it could be helpful to set up a dedicated status page for your various services.

One thing to note, even though you have `max-age=31536000; includeSubDomains; preload` set in your [HSTS header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) for `invidious.incogniweb.net`, your instance is not actually being preloaded by browsers. This is because the HSTS header needs to be set on your root domain `incogniweb.net` as well in order for preloading to work properly. You can find more information about this at [hstspreload.org](https://hstspreload.org/?domain=incogniweb.net).

In any case, your instance looks great overall and ready to be added to the official instance list.
