### ISSUE TITLE
[New instance] vid.selbsthilfegruppe.wtf

### ISSUE THREAD

**Issue by ParadoxLeon** [iv-org/documentation#534]
### URL

https://vid.selbsthilfegruppe.wtf

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Germany

### Man in the Middle

Cloudflare

**Comment by bugmaschine** [comment]
Hey @ParadoxLeon I checked your instance and noticed that it has Cloudflare Insights enabled, which are analytics. Disable the analytics on your instance and then your instance should be good to go.

 `<script defer="" src="https://static.cloudflareinsights.com/beacon.min.js/vef91dfe02fce4ee0ad053f6de4f175db1715022073587" integrity="sha512-sDIX0kl85v1Cl5tu4WGLZCpH/dV9OHbA4YlKCuCiMmOQIk4buzoYDZSFj+TvC71mOBLh8CDC/REgE0GX0xcbjA==" data-cf-beacon="{&quot;rayId&quot;:&quot;88b4e5ecedc76a4f&quot;,&quot;r&quot;:1,&quot;version&quot;:&quot;2024.4.1&quot;,&quot;token&quot;:&quot;7188e60479234817a4317944402d82bc&quot;}" crossorigin="anonymous"></script>`

**Comment by ParadoxLeon** [comment]
sorry totally forgot... its disabled now :)

**Comment by bugmaschine** [comment]
Your Instace has been now added

**Comment by bugmaschine** [comment]
@ParadoxLeon please change your Cloudflare settings to allow updown.io to monitor the Health of your instance. https://updown.io/doc/known-issues-when-monitoring-a-cloudflare-protected-website

**Comment by ParadoxLeon** [comment]
done :)

**Comment by perennialtech** [comment]
@ParadoxLeon Your instance has been temporarily removed from the official list (https://github.com/iv-org/documentation/commit/527dc1684ab8584df8ef2e08d519ef49fa1ee072).

Prior to adding your instance to the list, you were asked to remove external scripts (https://github.com/iv-org/documentation/issues/534#issuecomment-2136779974). While these scripts were not present when your instance was initially added, it appears they have since been re-added to the instance.

In order to be added back to the official list, you must remove these external scripts from your instance.

<details>
<summary><h3>External scripts found on the instance (click to expand)<h3></summary>
<pre>
<code>
  <script
  src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js"
  data-cf-settings="c78779e697c30c632f7e73c1-|49"
  defer
></script>
<script>
  (function () {
    if (!document.body) return;
    var js =
      "window['__CF$cv$params']={r:'88de748ebd0da81a',t:'MTcxNzQwNDgzMy40NDAwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";
    var _0xh = document.createElement("iframe");
    _0xh.height = 1;
    _0xh.width = 1;
    _0xh.style.position = "absolute";
    _0xh.style.top = 0;
    _0xh.style.left = 0;
    _0xh.style.border = "none";
    _0xh.style.visibility = "hidden";
    document.body.appendChild(_0xh);
    function handler() {
      var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;
      if (_0xi) {
        var _0xj = _0xi.createElement("script");
        _0xj.innerHTML = js;
        _0xi.getElementsByTagName("head")[0].appendChild(_0xj);
      }
    }
    if (document.readyState !== "loading") {
      handler();
    } else if (window.addEventListener) {
      document.addEventListener("DOMContentLoaded", handler);
    } else {
      var prev = document.onreadystatechange || function () {};
      document.onreadystatechange = function (e) {
        prev(e);
        if (document.readyState !== "loading") {
          document.onreadystatechange = prev;
          handler();
        }
      };
    }
  })();
</script>
</code>
</pre>
</details>

**Comment by ParadoxLeon** [comment]
I disabled RocketLoader, thought it'd be fine since it's for optimization

**Comment by ParadoxLeon** [comment]
Script disabled and Rotator set-up. https://github.com/iv-org/invidious/issues/4725#issuecomment-2154536790

**Comment by ParadoxLeon** [comment]
Instance closed
