### ISSUE TITLE
[New instance] https://invidious.darkness.services

### ISSUE THREAD

**Issue by blade10101** [iv-org/documentation#537]
### URL

https://invidious.darkness.services

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Man in the Middle

CloudFlare

### Additional information

10 Gbit Connection

**Comment by perennialtech** [comment]
@blade10101 Thanks for submitting your instance. However, you need to address the following before it can be added after the 30 day wait for uptime:

- Please disable [Cloudflare JavaScript detections](https://developers.cloudflare.com/bots/reference/javascript-detections) on your instance.
  ```html
  <script>
    (function () {
      if (!document.body) return;
      var js =
        "window['__CF$cv$params']={r:'8779e91e2feb5d21',t:'MTcxMzY2NjE5MS43NDcwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";
      var _0xh = document.createElement("iframe");
      _0xh.height = 1;
      _0xh.width = 1;
      _0xh.style.position = "absolute";
      _0xh.style.top = 0;
      _0xh.style.left = 0;
      _0xh.style.border = "none";
      _0xh.style.visibility = "hidden";
      document.body.appendChild(_0xh);
      function handler() {
        var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;
        if (_0xi) {
          var _0xj = _0xi.createElement("script");
          _0xj.innerHTML = js;
          _0xi.getElementsByTagName("head")[0].appendChild(_0xj);
        }
      }
      if (document.readyState !== "loading") {
        handler();
      } else if (window.addEventListener) {
        document.addEventListener("DOMContentLoaded", handler);
      } else {
        var prev = document.onreadystatechange || function () {};
        document.onreadystatechange = function (e) {
          prev(e);
          if (document.readyState !== "loading") {
            document.onreadystatechange = prev;
            handler();
          }
        };
      }
    })();
  </script>
  ```
- As the GitHub bot mentioned, make sure that you've followed https://docs.invidious.io/ipv6-rotator/ and https://docs.invidious.io/improve-public-instance/.
- While it's not required, consider removing the [`X-XSS-Protection`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) header, since it's been deprecated for a while now and no modern browser supports it.

**Comment by blade10101** [comment]
I addressed the issues, or I believe I have :)

Apr 20, 2024 10:34:27 PM perennial ***@***.***>:

**Comment by perennialtech** [comment]
@blade10101 Your instance looks good now, but just a heads up that you're actually setting the `X-XSS-Protection` header twice, rather than removing it entirely.

If you're using nginx, consider using the [`more_clear_headers`](https://github.com/openresty/headers-more-nginx-module#more_clear_headers) directive from the [`ngx_headers_more`](https://github.com/openresty/headers-more-nginx-module) module to properly remove the header.

**Comment by blade10101** [comment]
From what I gather, I have to recompile nginx outside of docker? Because I set the header as 0 so it didn't have it set.

Apr 21, 2024 10:07:05 PM perennial ***@***.***>:

**Comment by unixfox** [comment]
You don't need to do anything with the header. Please remove any modification that you are doing for the header X-XSS-Protection on your nginx.
Thank you.

**Comment by blade10101** [comment]
I did that this morning.

Apr 22, 2024 8:50:50 AM Émilien (perso) ***@***.***>:
