### ISSUE TITLE
[New instance] inv.n8pjl.ca

### ISSUE THREAD

**Issue by n8pjl** [iv-org/documentation#560]
### URL

https://inv.n8pjl.ca/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled
- [X] Instance is properly configured (including the mandatory [post install configuration](https://docs.invidious.io/installation/#post-install-configuration))
- [X] Instance has an automatic hourly restart setup of Invidious
- [X] If dash, proxy + download is enabled (default settings), the instance has unlimited traffic/bandwidth or close to unlimited (100TB minimum)
- [X] Instance is not running any kind of analytics

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

Canada

### Your matrix username

@saladin:n8pjl.ca

### Additional information

This instance has been public before and nothing has changed in the configuration since then.

I'm hoping that the relisting can be expedited. I simply do not need the excess capacity on this server anymore, and do not expect to need it anytime soon.

**Comment by perennialtech** [comment]
@n8pjl Apologies for not reviewing your instance sooner.

In terms of uptime, your instance looks fine at [>99% monthly rolling uptime](https://updown.io/f8dc). Account creation and preferences also work properly.

However, there are a few issues that should be addressed:

1. Although you've set `max-age=31536000; includeSubDomains; preload` for your [HSTS header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security), your instance is not being preloaded. This is because the correct HSTS header needs to be set on the root domain `n8pjl.ca` as well. Refer to [hstspreload.org](https://hstspreload.org/?domain=n8pjl.ca) for more information on setting this up properly.

2. Playback seems to be broken on your instance at the moment, with video pages returning HTTP 500 and the `Watch on the latest version of YouTube` error message. Make sure that you have set up IPv6 address rotation correctly according to the [documentation](https://docs.invidious.io/ipv6-rotator/).

3. This is mostly a nitpick, but your instance is currently including a rather specific `server` header in its responses. You may want to review the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server) on this header and decide if you wish to continue including it or not.

**Comment by n8pjl** [comment]
I'm sunsetting this instance to be shut down in October. I no longer wish for the domain to be listed.
